server:
  port: 8888

spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    # No restrictions on table names
    url: jdbc:h2:mem:h2
    # No restrictions on username and password
    username: root
    password: 123456

#mybatis
mybatis:
  type-aliases-package: com.ikyxxs.adengine.domain.entity
  mapper-locations: classpath:/mybatis/*.xml
